-- AlterTable
ALTER TABLE `reputation_ledger` MODIFY `reason` ENUM('HUB_REPLY_HELPFUL', 'BLOG_QUALITY', 'BLOG_POST_LIKED', 'BLOG_COMMENT_HELPFUL', 'MOD_ADJUSTMENT', 'ADMIN_BONUS', 'ADMIN_PENALTY') NOT NULL;
