export const ErrorCode = {
    UNAUTHENTICATED: "UNAUTHENTICATED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RATE_LIMITED: "RATE_LIMITED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    HTTP_ERROR: "HTTP_ERROR",
    EMAIL_TAKEN: "EMAIL_TAKEN",
    USERNAME_TAKEN: "USERNAME_TAKEN",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_EXISTS_PASSWORD: "ACCOUNT_EXISTS_PASSWORD",
    AUTH_IDENTITY_CONFLICT: "AUTH_IDENTITY_CONFLICT",
    INVALID_OR_EXPIRED_TOKEN: "INVALID_OR_EXPIRED_TOKEN",
    OAUTH_ACCOUNT_HINT: "OAUTH_ACCOUNT_HINT",
    HUB_SLUG_TAKEN: "HUB_SLUG_TAKEN",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
